/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TreatmentPlansRouteImport } from './routes/treatment-plans'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatientPortalRouteImport } from './routes/patient-portal'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ImagingRouteImport } from './routes/imaging'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DentalChartRouteImport } from './routes/dental-chart'
import { Route as ConsentFormsRouteImport } from './routes/consent-forms'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClinicalRecordsRouteImport } from './routes/clinical-records'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentPlansRoute = TreatmentPlansRouteImport.update({
  id: '/treatment-plans',
  path: '/treatment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalRoute = PatientPortalRouteImport.update({
  id: '/patient-portal',
  path: '/patient-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagingRoute = ImagingRouteImport.update({
  id: '/imaging',
  path: '/imaging',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartRoute = DentalChartRouteImport.update({
  id: '/dental-chart',
  path: '/dental-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentFormsRoute = ConsentFormsRouteImport.update({
  id: '/consent-forms',
  path: '/consent-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRecordsRoute = ClinicalRecordsRouteImport.update({
  id: '/clinical-records',
  path: '/clinical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/clinical-records': typeof ClinicalRecordsRoute
  '/communication': typeof CommunicationRoute
  '/consent-forms': typeof ConsentFormsRoute
  '/dental-chart': typeof DentalChartRoute
  '/documents': typeof DocumentsRoute
  '/imaging': typeof ImagingRoute
  '/insurance': typeof InsuranceRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/marketing': typeof MarketingRoute
  '/patient-portal': typeof PatientPortalRoute
  '/patients': typeof PatientsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/users': typeof UsersRoute
  '/website': typeof WebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/clinical-records': typeof ClinicalRecordsRoute
  '/communication': typeof CommunicationRoute
  '/consent-forms': typeof ConsentFormsRoute
  '/dental-chart': typeof DentalChartRoute
  '/documents': typeof DocumentsRoute
  '/imaging': typeof ImagingRoute
  '/insurance': typeof InsuranceRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/marketing': typeof MarketingRoute
  '/patient-portal': typeof PatientPortalRoute
  '/patients': typeof PatientsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/users': typeof UsersRoute
  '/website': typeof WebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/clinical-records': typeof ClinicalRecordsRoute
  '/communication': typeof CommunicationRoute
  '/consent-forms': typeof ConsentFormsRoute
  '/dental-chart': typeof DentalChartRoute
  '/documents': typeof DocumentsRoute
  '/imaging': typeof ImagingRoute
  '/insurance': typeof InsuranceRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/marketing': typeof MarketingRoute
  '/patient-portal': typeof PatientPortalRoute
  '/patients': typeof PatientsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/users': typeof UsersRoute
  '/website': typeof WebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/clinical-records'
    | '/communication'
    | '/consent-forms'
    | '/dental-chart'
    | '/documents'
    | '/imaging'
    | '/insurance'
    | '/inventory'
    | '/laboratory'
    | '/marketing'
    | '/patient-portal'
    | '/patients'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/treatment-plans'
    | '/users'
    | '/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/clinical-records'
    | '/communication'
    | '/consent-forms'
    | '/dental-chart'
    | '/documents'
    | '/imaging'
    | '/insurance'
    | '/inventory'
    | '/laboratory'
    | '/marketing'
    | '/patient-portal'
    | '/patients'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/treatment-plans'
    | '/users'
    | '/website'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/clinical-records'
    | '/communication'
    | '/consent-forms'
    | '/dental-chart'
    | '/documents'
    | '/imaging'
    | '/insurance'
    | '/inventory'
    | '/laboratory'
    | '/marketing'
    | '/patient-portal'
    | '/patients'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/treatment-plans'
    | '/users'
    | '/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  ClinicalRecordsRoute: typeof ClinicalRecordsRoute
  CommunicationRoute: typeof CommunicationRoute
  ConsentFormsRoute: typeof ConsentFormsRoute
  DentalChartRoute: typeof DentalChartRoute
  DocumentsRoute: typeof DocumentsRoute
  ImagingRoute: typeof ImagingRoute
  InsuranceRoute: typeof InsuranceRoute
  InventoryRoute: typeof InventoryRoute
  LaboratoryRoute: typeof LaboratoryRoute
  MarketingRoute: typeof MarketingRoute
  PatientPortalRoute: typeof PatientPortalRoute
  PatientsRoute: typeof PatientsRoute
  QueueRoute: typeof QueueRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TreatmentPlansRoute: typeof TreatmentPlansRoute
  UsersRoute: typeof UsersRoute
  WebsiteRoute: typeof WebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment-plans': {
      id: '/treatment-plans'
      path: '/treatment-plans'
      fullPath: '/treatment-plans'
      preLoaderRoute: typeof TreatmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal': {
      id: '/patient-portal'
      path: '/patient-portal'
      fullPath: '/patient-portal'
      preLoaderRoute: typeof PatientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging': {
      id: '/imaging'
      path: '/imaging'
      fullPath: '/imaging'
      preLoaderRoute: typeof ImagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chart': {
      id: '/dental-chart'
      path: '/dental-chart'
      fullPath: '/dental-chart'
      preLoaderRoute: typeof DentalChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent-forms': {
      id: '/consent-forms'
      path: '/consent-forms'
      fullPath: '/consent-forms'
      preLoaderRoute: typeof ConsentFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-records': {
      id: '/clinical-records'
      path: '/clinical-records'
      fullPath: '/clinical-records'
      preLoaderRoute: typeof ClinicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  ClinicalRecordsRoute: ClinicalRecordsRoute,
  CommunicationRoute: CommunicationRoute,
  ConsentFormsRoute: ConsentFormsRoute,
  DentalChartRoute: DentalChartRoute,
  DocumentsRoute: DocumentsRoute,
  ImagingRoute: ImagingRoute,
  InsuranceRoute: InsuranceRoute,
  InventoryRoute: InventoryRoute,
  LaboratoryRoute: LaboratoryRoute,
  MarketingRoute: MarketingRoute,
  PatientPortalRoute: PatientPortalRoute,
  PatientsRoute: PatientsRoute,
  QueueRoute: QueueRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SubscriptionRoute: SubscriptionRoute,
  TreatmentPlansRoute: TreatmentPlansRoute,
  UsersRoute: UsersRoute,
  WebsiteRoute: WebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
