/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as ClinicWebsiteRouteImport } from './routes/clinic.website'
import { Route as ClinicUsersRouteImport } from './routes/clinic.users'
import { Route as ClinicTreatmentPlansRouteImport } from './routes/clinic.treatment-plans'
import { Route as ClinicSubscriptionRouteImport } from './routes/clinic.subscription'
import { Route as ClinicStaffRouteImport } from './routes/clinic.staff'
import { Route as ClinicSettingsRouteImport } from './routes/clinic.settings'
import { Route as ClinicReportsRouteImport } from './routes/clinic.reports'
import { Route as ClinicQueueRouteImport } from './routes/clinic.queue'
import { Route as ClinicPatientsRouteImport } from './routes/clinic.patients'
import { Route as ClinicPatientPortalRouteImport } from './routes/clinic.patient-portal'
import { Route as ClinicMarketingRouteImport } from './routes/clinic.marketing'
import { Route as ClinicLaboratoryRouteImport } from './routes/clinic.laboratory'
import { Route as ClinicInventoryRouteImport } from './routes/clinic.inventory'
import { Route as ClinicInsuranceRouteImport } from './routes/clinic.insurance'
import { Route as ClinicImagingRouteImport } from './routes/clinic.imaging'
import { Route as ClinicDocumentsRouteImport } from './routes/clinic.documents'
import { Route as ClinicDentalChartRouteImport } from './routes/clinic.dental-chart'
import { Route as ClinicConsentFormsRouteImport } from './routes/clinic.consent-forms'
import { Route as ClinicCommunicationRouteImport } from './routes/clinic.communication'
import { Route as ClinicClinicalRecordsRouteImport } from './routes/clinic.clinical-records'
import { Route as ClinicBillingRouteImport } from './routes/clinic.billing'
import { Route as ClinicAppointmentsRouteImport } from './routes/clinic.appointments'
import { Route as ClinicAnalyticsRouteImport } from './routes/clinic.analytics'

const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/clinic/',
  path: '/clinic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicWebsiteRoute = ClinicWebsiteRouteImport.update({
  id: '/clinic/website',
  path: '/clinic/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicUsersRoute = ClinicUsersRouteImport.update({
  id: '/clinic/users',
  path: '/clinic/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicTreatmentPlansRoute = ClinicTreatmentPlansRouteImport.update({
  id: '/clinic/treatment-plans',
  path: '/clinic/treatment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicSubscriptionRoute = ClinicSubscriptionRouteImport.update({
  id: '/clinic/subscription',
  path: '/clinic/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicStaffRoute = ClinicStaffRouteImport.update({
  id: '/clinic/staff',
  path: '/clinic/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicSettingsRoute = ClinicSettingsRouteImport.update({
  id: '/clinic/settings',
  path: '/clinic/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicReportsRoute = ClinicReportsRouteImport.update({
  id: '/clinic/reports',
  path: '/clinic/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicQueueRoute = ClinicQueueRouteImport.update({
  id: '/clinic/queue',
  path: '/clinic/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPatientsRoute = ClinicPatientsRouteImport.update({
  id: '/clinic/patients',
  path: '/clinic/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPatientPortalRoute = ClinicPatientPortalRouteImport.update({
  id: '/clinic/patient-portal',
  path: '/clinic/patient-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicMarketingRoute = ClinicMarketingRouteImport.update({
  id: '/clinic/marketing',
  path: '/clinic/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicLaboratoryRoute = ClinicLaboratoryRouteImport.update({
  id: '/clinic/laboratory',
  path: '/clinic/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicInventoryRoute = ClinicInventoryRouteImport.update({
  id: '/clinic/inventory',
  path: '/clinic/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicInsuranceRoute = ClinicInsuranceRouteImport.update({
  id: '/clinic/insurance',
  path: '/clinic/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicImagingRoute = ClinicImagingRouteImport.update({
  id: '/clinic/imaging',
  path: '/clinic/imaging',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicDocumentsRoute = ClinicDocumentsRouteImport.update({
  id: '/clinic/documents',
  path: '/clinic/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicDentalChartRoute = ClinicDentalChartRouteImport.update({
  id: '/clinic/dental-chart',
  path: '/clinic/dental-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicConsentFormsRoute = ClinicConsentFormsRouteImport.update({
  id: '/clinic/consent-forms',
  path: '/clinic/consent-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicCommunicationRoute = ClinicCommunicationRouteImport.update({
  id: '/clinic/communication',
  path: '/clinic/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicalRecordsRoute = ClinicClinicalRecordsRouteImport.update({
  id: '/clinic/clinical-records',
  path: '/clinic/clinical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicBillingRoute = ClinicBillingRouteImport.update({
  id: '/clinic/billing',
  path: '/clinic/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicAppointmentsRoute = ClinicAppointmentsRouteImport.update({
  id: '/clinic/appointments',
  path: '/clinic/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicAnalyticsRoute = ClinicAnalyticsRouteImport.update({
  id: '/clinic/analytics',
  path: '/clinic/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/clinic/analytics': typeof ClinicAnalyticsRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/billing': typeof ClinicBillingRoute
  '/clinic/clinical-records': typeof ClinicClinicalRecordsRoute
  '/clinic/communication': typeof ClinicCommunicationRoute
  '/clinic/consent-forms': typeof ClinicConsentFormsRoute
  '/clinic/dental-chart': typeof ClinicDentalChartRoute
  '/clinic/documents': typeof ClinicDocumentsRoute
  '/clinic/imaging': typeof ClinicImagingRoute
  '/clinic/insurance': typeof ClinicInsuranceRoute
  '/clinic/inventory': typeof ClinicInventoryRoute
  '/clinic/laboratory': typeof ClinicLaboratoryRoute
  '/clinic/marketing': typeof ClinicMarketingRoute
  '/clinic/patient-portal': typeof ClinicPatientPortalRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/queue': typeof ClinicQueueRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/clinic/settings': typeof ClinicSettingsRoute
  '/clinic/staff': typeof ClinicStaffRoute
  '/clinic/subscription': typeof ClinicSubscriptionRoute
  '/clinic/treatment-plans': typeof ClinicTreatmentPlansRoute
  '/clinic/users': typeof ClinicUsersRoute
  '/clinic/website': typeof ClinicWebsiteRoute
  '/clinic/': typeof ClinicIndexRoute
}
export interface FileRoutesByTo {
  '/clinic/analytics': typeof ClinicAnalyticsRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/billing': typeof ClinicBillingRoute
  '/clinic/clinical-records': typeof ClinicClinicalRecordsRoute
  '/clinic/communication': typeof ClinicCommunicationRoute
  '/clinic/consent-forms': typeof ClinicConsentFormsRoute
  '/clinic/dental-chart': typeof ClinicDentalChartRoute
  '/clinic/documents': typeof ClinicDocumentsRoute
  '/clinic/imaging': typeof ClinicImagingRoute
  '/clinic/insurance': typeof ClinicInsuranceRoute
  '/clinic/inventory': typeof ClinicInventoryRoute
  '/clinic/laboratory': typeof ClinicLaboratoryRoute
  '/clinic/marketing': typeof ClinicMarketingRoute
  '/clinic/patient-portal': typeof ClinicPatientPortalRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/queue': typeof ClinicQueueRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/clinic/settings': typeof ClinicSettingsRoute
  '/clinic/staff': typeof ClinicStaffRoute
  '/clinic/subscription': typeof ClinicSubscriptionRoute
  '/clinic/treatment-plans': typeof ClinicTreatmentPlansRoute
  '/clinic/users': typeof ClinicUsersRoute
  '/clinic/website': typeof ClinicWebsiteRoute
  '/clinic': typeof ClinicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/clinic/analytics': typeof ClinicAnalyticsRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/billing': typeof ClinicBillingRoute
  '/clinic/clinical-records': typeof ClinicClinicalRecordsRoute
  '/clinic/communication': typeof ClinicCommunicationRoute
  '/clinic/consent-forms': typeof ClinicConsentFormsRoute
  '/clinic/dental-chart': typeof ClinicDentalChartRoute
  '/clinic/documents': typeof ClinicDocumentsRoute
  '/clinic/imaging': typeof ClinicImagingRoute
  '/clinic/insurance': typeof ClinicInsuranceRoute
  '/clinic/inventory': typeof ClinicInventoryRoute
  '/clinic/laboratory': typeof ClinicLaboratoryRoute
  '/clinic/marketing': typeof ClinicMarketingRoute
  '/clinic/patient-portal': typeof ClinicPatientPortalRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/queue': typeof ClinicQueueRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/clinic/settings': typeof ClinicSettingsRoute
  '/clinic/staff': typeof ClinicStaffRoute
  '/clinic/subscription': typeof ClinicSubscriptionRoute
  '/clinic/treatment-plans': typeof ClinicTreatmentPlansRoute
  '/clinic/users': typeof ClinicUsersRoute
  '/clinic/website': typeof ClinicWebsiteRoute
  '/clinic/': typeof ClinicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clinic/analytics'
    | '/clinic/appointments'
    | '/clinic/billing'
    | '/clinic/clinical-records'
    | '/clinic/communication'
    | '/clinic/consent-forms'
    | '/clinic/dental-chart'
    | '/clinic/documents'
    | '/clinic/imaging'
    | '/clinic/insurance'
    | '/clinic/inventory'
    | '/clinic/laboratory'
    | '/clinic/marketing'
    | '/clinic/patient-portal'
    | '/clinic/patients'
    | '/clinic/queue'
    | '/clinic/reports'
    | '/clinic/settings'
    | '/clinic/staff'
    | '/clinic/subscription'
    | '/clinic/treatment-plans'
    | '/clinic/users'
    | '/clinic/website'
    | '/clinic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clinic/analytics'
    | '/clinic/appointments'
    | '/clinic/billing'
    | '/clinic/clinical-records'
    | '/clinic/communication'
    | '/clinic/consent-forms'
    | '/clinic/dental-chart'
    | '/clinic/documents'
    | '/clinic/imaging'
    | '/clinic/insurance'
    | '/clinic/inventory'
    | '/clinic/laboratory'
    | '/clinic/marketing'
    | '/clinic/patient-portal'
    | '/clinic/patients'
    | '/clinic/queue'
    | '/clinic/reports'
    | '/clinic/settings'
    | '/clinic/staff'
    | '/clinic/subscription'
    | '/clinic/treatment-plans'
    | '/clinic/users'
    | '/clinic/website'
    | '/clinic'
  id:
    | '__root__'
    | '/clinic/analytics'
    | '/clinic/appointments'
    | '/clinic/billing'
    | '/clinic/clinical-records'
    | '/clinic/communication'
    | '/clinic/consent-forms'
    | '/clinic/dental-chart'
    | '/clinic/documents'
    | '/clinic/imaging'
    | '/clinic/insurance'
    | '/clinic/inventory'
    | '/clinic/laboratory'
    | '/clinic/marketing'
    | '/clinic/patient-portal'
    | '/clinic/patients'
    | '/clinic/queue'
    | '/clinic/reports'
    | '/clinic/settings'
    | '/clinic/staff'
    | '/clinic/subscription'
    | '/clinic/treatment-plans'
    | '/clinic/users'
    | '/clinic/website'
    | '/clinic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClinicAnalyticsRoute: typeof ClinicAnalyticsRoute
  ClinicAppointmentsRoute: typeof ClinicAppointmentsRoute
  ClinicBillingRoute: typeof ClinicBillingRoute
  ClinicClinicalRecordsRoute: typeof ClinicClinicalRecordsRoute
  ClinicCommunicationRoute: typeof ClinicCommunicationRoute
  ClinicConsentFormsRoute: typeof ClinicConsentFormsRoute
  ClinicDentalChartRoute: typeof ClinicDentalChartRoute
  ClinicDocumentsRoute: typeof ClinicDocumentsRoute
  ClinicImagingRoute: typeof ClinicImagingRoute
  ClinicInsuranceRoute: typeof ClinicInsuranceRoute
  ClinicInventoryRoute: typeof ClinicInventoryRoute
  ClinicLaboratoryRoute: typeof ClinicLaboratoryRoute
  ClinicMarketingRoute: typeof ClinicMarketingRoute
  ClinicPatientPortalRoute: typeof ClinicPatientPortalRoute
  ClinicPatientsRoute: typeof ClinicPatientsRoute
  ClinicQueueRoute: typeof ClinicQueueRoute
  ClinicReportsRoute: typeof ClinicReportsRoute
  ClinicSettingsRoute: typeof ClinicSettingsRoute
  ClinicStaffRoute: typeof ClinicStaffRoute
  ClinicSubscriptionRoute: typeof ClinicSubscriptionRoute
  ClinicTreatmentPlansRoute: typeof ClinicTreatmentPlansRoute
  ClinicUsersRoute: typeof ClinicUsersRoute
  ClinicWebsiteRoute: typeof ClinicWebsiteRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clinic/': {
      id: '/clinic/'
      path: '/clinic'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/website': {
      id: '/clinic/website'
      path: '/clinic/website'
      fullPath: '/clinic/website'
      preLoaderRoute: typeof ClinicWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/users': {
      id: '/clinic/users'
      path: '/clinic/users'
      fullPath: '/clinic/users'
      preLoaderRoute: typeof ClinicUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/treatment-plans': {
      id: '/clinic/treatment-plans'
      path: '/clinic/treatment-plans'
      fullPath: '/clinic/treatment-plans'
      preLoaderRoute: typeof ClinicTreatmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/subscription': {
      id: '/clinic/subscription'
      path: '/clinic/subscription'
      fullPath: '/clinic/subscription'
      preLoaderRoute: typeof ClinicSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/staff': {
      id: '/clinic/staff'
      path: '/clinic/staff'
      fullPath: '/clinic/staff'
      preLoaderRoute: typeof ClinicStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/settings': {
      id: '/clinic/settings'
      path: '/clinic/settings'
      fullPath: '/clinic/settings'
      preLoaderRoute: typeof ClinicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/reports': {
      id: '/clinic/reports'
      path: '/clinic/reports'
      fullPath: '/clinic/reports'
      preLoaderRoute: typeof ClinicReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/queue': {
      id: '/clinic/queue'
      path: '/clinic/queue'
      fullPath: '/clinic/queue'
      preLoaderRoute: typeof ClinicQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/patients': {
      id: '/clinic/patients'
      path: '/clinic/patients'
      fullPath: '/clinic/patients'
      preLoaderRoute: typeof ClinicPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/patient-portal': {
      id: '/clinic/patient-portal'
      path: '/clinic/patient-portal'
      fullPath: '/clinic/patient-portal'
      preLoaderRoute: typeof ClinicPatientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/marketing': {
      id: '/clinic/marketing'
      path: '/clinic/marketing'
      fullPath: '/clinic/marketing'
      preLoaderRoute: typeof ClinicMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/laboratory': {
      id: '/clinic/laboratory'
      path: '/clinic/laboratory'
      fullPath: '/clinic/laboratory'
      preLoaderRoute: typeof ClinicLaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/inventory': {
      id: '/clinic/inventory'
      path: '/clinic/inventory'
      fullPath: '/clinic/inventory'
      preLoaderRoute: typeof ClinicInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/insurance': {
      id: '/clinic/insurance'
      path: '/clinic/insurance'
      fullPath: '/clinic/insurance'
      preLoaderRoute: typeof ClinicInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/imaging': {
      id: '/clinic/imaging'
      path: '/clinic/imaging'
      fullPath: '/clinic/imaging'
      preLoaderRoute: typeof ClinicImagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/documents': {
      id: '/clinic/documents'
      path: '/clinic/documents'
      fullPath: '/clinic/documents'
      preLoaderRoute: typeof ClinicDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/dental-chart': {
      id: '/clinic/dental-chart'
      path: '/clinic/dental-chart'
      fullPath: '/clinic/dental-chart'
      preLoaderRoute: typeof ClinicDentalChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/consent-forms': {
      id: '/clinic/consent-forms'
      path: '/clinic/consent-forms'
      fullPath: '/clinic/consent-forms'
      preLoaderRoute: typeof ClinicConsentFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/communication': {
      id: '/clinic/communication'
      path: '/clinic/communication'
      fullPath: '/clinic/communication'
      preLoaderRoute: typeof ClinicCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/clinical-records': {
      id: '/clinic/clinical-records'
      path: '/clinic/clinical-records'
      fullPath: '/clinic/clinical-records'
      preLoaderRoute: typeof ClinicClinicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/billing': {
      id: '/clinic/billing'
      path: '/clinic/billing'
      fullPath: '/clinic/billing'
      preLoaderRoute: typeof ClinicBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/appointments': {
      id: '/clinic/appointments'
      path: '/clinic/appointments'
      fullPath: '/clinic/appointments'
      preLoaderRoute: typeof ClinicAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/analytics': {
      id: '/clinic/analytics'
      path: '/clinic/analytics'
      fullPath: '/clinic/analytics'
      preLoaderRoute: typeof ClinicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ClinicAnalyticsRoute: ClinicAnalyticsRoute,
  ClinicAppointmentsRoute: ClinicAppointmentsRoute,
  ClinicBillingRoute: ClinicBillingRoute,
  ClinicClinicalRecordsRoute: ClinicClinicalRecordsRoute,
  ClinicCommunicationRoute: ClinicCommunicationRoute,
  ClinicConsentFormsRoute: ClinicConsentFormsRoute,
  ClinicDentalChartRoute: ClinicDentalChartRoute,
  ClinicDocumentsRoute: ClinicDocumentsRoute,
  ClinicImagingRoute: ClinicImagingRoute,
  ClinicInsuranceRoute: ClinicInsuranceRoute,
  ClinicInventoryRoute: ClinicInventoryRoute,
  ClinicLaboratoryRoute: ClinicLaboratoryRoute,
  ClinicMarketingRoute: ClinicMarketingRoute,
  ClinicPatientPortalRoute: ClinicPatientPortalRoute,
  ClinicPatientsRoute: ClinicPatientsRoute,
  ClinicQueueRoute: ClinicQueueRoute,
  ClinicReportsRoute: ClinicReportsRoute,
  ClinicSettingsRoute: ClinicSettingsRoute,
  ClinicStaffRoute: ClinicStaffRoute,
  ClinicSubscriptionRoute: ClinicSubscriptionRoute,
  ClinicTreatmentPlansRoute: ClinicTreatmentPlansRoute,
  ClinicUsersRoute: ClinicUsersRoute,
  ClinicWebsiteRoute: ClinicWebsiteRoute,
  ClinicIndexRoute: ClinicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
